using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using UnityEditor;
using UnityEngine;

//This was mainly generated by AI and base source code was the video reference.
//Chat history: https://chatgpt.com/share/69094c3a-20c4-8000-affa-70f173ec01d4
public class TerrainWindow : ExtendedWindow
{
    private MapTerrain targetAsset;

    private readonly Dictionary<string, bool> _groupOpen = new();

    public static void Open(MapTerrain mapTerrain)
    {
        var window = GetWindow<TerrainWindow>("Game Data Editor");
        window.targetAsset = mapTerrain;
        window.serializedObject = new SerializedObject(mapTerrain);
        window.Repaint();
    }

    private void OnEnable()
    {
        if (targetAsset != null && (serializedObject == null || serializedObject.targetObject == null))
            serializedObject = new SerializedObject(targetAsset);
    }

    private void OnGUI()
    {
        if (serializedObject == null || serializedObject.targetObject == null)
        {
            EditorGUILayout.HelpBox("No MapTerrain selected. Open this window from a MapTerrain asset.", MessageType.Info);
            return;
        }

        serializedObject.Update();

        var topLevel = GetTopLevelProps(serializedObject);

        //Builds automatic groups from [Header] attributes
        var groups = BuildGroupsByHeader(targetAsset, topLevel);

        //Draws all groups
        foreach (var (groupName, props) in groups)
        {
            if (!_groupOpen.ContainsKey(groupName)) _groupOpen[groupName] = true;
            _groupOpen[groupName] = EditorGUILayout.Foldout(_groupOpen[groupName], groupName, true);
            if (!_groupOpen[groupName]) continue;

            using (new EditorGUILayout.VerticalScope("box"))
            {
                foreach (var p in props)
                    EditorGUILayout.PropertyField(p, true);
            }

            EditorGUILayout.Space(3);
        }

        serializedObject.ApplyModifiedProperties();
        
        //generate Button
        EditorGUILayout.Space(10);
        EditorGUILayout.LabelField("", GUI.skin.horizontalSlider);

        if (GUILayout.Button("Generate Map", GUILayout.Height(30)))
        {
            MapGenerator generator = FindObjectOfType<MapGenerator>();
            if (generator != null)
            {
                generator.mapTerrain = targetAsset;
                generator.GenerateMap();
            }
        }
    }

    private static List<SerializedProperty> GetTopLevelProps(SerializedObject so)
    {
        var list = new List<SerializedProperty>();
        var it = so.GetIterator();
        var enterChildren = true;
        while (it.NextVisible(enterChildren))
        {
            enterChildren = false;
            if (it.depth != 0) continue;
            if (it.name == "m_Script") continue;
            list.Add(so.FindProperty(it.propertyPath)); // clone the property reference
        }
        return list;
    }

    private static SortedDictionary<string, List<SerializedProperty>> BuildGroupsByHeader(ScriptableObject target, List<SerializedProperty> props)
    {
        var result = new SortedDictionary<string, List<SerializedProperty>>();
        var type = target.GetType();
        const BindingFlags bf = BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic;

        foreach (var p in props)
        {
            var field = type.GetField(p.name, bf);
            string group = "Other";
            if (field != null)
            {
                var header = field.GetCustomAttribute<HeaderAttribute>();
                if (header != null && !string.IsNullOrEmpty(header.header))
                    group = header.header;
            }

            if (!result.TryGetValue(group, out var list))
            {
                list = new List<SerializedProperty>();
                result[group] = list;
            }
            list.Add(p);
        }

        foreach (var key in result.Keys.ToList())
            result[key] = result[key].OrderBy(p => FieldOrder(type, p.name)).ToList();

        return result;
    }

    //Saves field order
    private static int FieldOrder(Type t, string fieldName)
    {
        const BindingFlags bf = BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.DeclaredOnly;
        var fields = new List<FieldInfo>();
        for (var type = t; type != null && type != typeof(UnityEngine.Object); type = type.BaseType)
            fields.AddRange(type.GetFields(bf));
        for (int i = 0; i < fields.Count; i++)
            if (fields[i].Name == fieldName) return i;
        return int.MaxValue;
    }
}
